---
- name: Install Python dependencies
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install python3-six
      apt:
        name: python3-six
        state: present