# ansible/playbooks/deploy_ml_app.yml
---
- name: Deploy the ML application container
  hosts: ml_app
  become: yes
  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"

    - name: Pull the ml-app image
      community.docker.docker_image:
        name: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/ml-app:v2"  # <-- Change this line
        source: pull
        state: present

    - name: Stop and remove old ml-app container if it exists
      community.docker.docker_container:
        name: ml-app-container
        state: absent
      ignore_errors: yes

    - name: Run the new ml-app container
      community.docker.docker_container:
        name: ml-app-container
        image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/ml-app:v2"  # <-- And this line
        state: started
        pull: yes
        published_ports:
          - "5000:5000"